name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Build documentation
        run: |
          docs/make_docs.sh
